<?php
namespace Pulsestorm\ToDoCrud\Block;

use Magento\Framework\View\Element\Template;

class MyMain extends Template
{
    protected $toDoFactory;

    public function __construct(
//            \Magento\Framework\View\Element\Template\Context $context,
            \Pulsestorm\ToDoCrud\Model\TodoItemFactory $toDoFactory
        )
    {
        $this->toDoFactory = $toDoFactory;
     //   parent::__construct($context);
    }

    protected function _prepareLayout()
    {
        $todo = $this->toDoFactory->create();

        $todo = $todo->load(1);
        var_dump($todo->getData());

        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}