<?php
namespace Pulsestorm\ToDoCrud\Block;

use Magento\Framework\View\Element\Template;

class MyMain extends Template
{
    protected $toDoFactory;

    public function __construct(
            \Magento\Framework\View\Element\Template\Context $context,
            \Pulsestorm\ToDoCrud\Model\TodoItemFactory $toDoFactory
        )
    {
        $this->toDoFactory = $toDoFactory;
        parent::__construct($context);
    }

    protected function _prepareLayout()
    {
        var_dump(
            get_class($this->toDoFactory)
        );
        exit;
//        var_dump(__METHOD__);
//        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}